# Generated by Django 5.2.1 on 2025-06-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escola_user_participante_user_prova_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='id_participante',
        ),
        migrations.RemoveField(
            model_name='prova',
            name='id_prova',
        ),
    ]
