# Generated by Django 5.2.1 on 2025-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_participante_id_participante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='prova',
            name='nivel',
            field=models.CharField(default='Ini_1', max_length=32),
        ),
    ]
