# Generated by Django 5.2.1 on 2025-06-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prova_ano_prova_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='fase',
            field=models.CharField(default='Fase 1', max_length=32),
        ),
    ]
