# Generated by Django 5.2.1 on 2025-06-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prova_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='ano',
            field=models.CharField(choices=[('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='prova',
            name='fase',
            field=models.CharField(choices=[('Fase 1', 'Fase 1'), ('Fase 2', 'Fase 2')], default='Fase 1', max_length=10),
        ),
        migrations.AlterField(
            model_name='prova',
            name='nivel',
            field=models.CharField(choices=[('Iniciacao A', 'Iniciação A'), ('Iniciacao B', 'Iniciação B'), ('Programacao', 'Programação')], default='Iniciacao A', max_length=20),
        ),
    ]
