# Generated by Django 5.2.3 on 2025-06-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_prova_ano_alter_prova_fase_alter_prova_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='id_prova',
            field=models.CharField(default='001', max_length=3, unique=True),
        ),
    ]
