# Generated by Django 5.2.3 on 2025-06-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prova_id_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='id_escola',
            field=models.CharField(default='001', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='id_participante',
            field=models.CharField(default='001', max_length=3, unique=True),
        ),
    ]
