# Generated by Django 5.2.3 on 2025-06-12 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prova_id_prova'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GabaritoLido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gabarito_lido', models.CharField(max_length=20)),
                ('nota', models.FloatField(default=0.0)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prova')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
