# Generated by Django 5.2.3 on 2025-06-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gabaritolido'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabaritolido',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.participante'),
        ),
    ]
