# Generated by Django 5.2.3 on 2025-06-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_escola_id_escola_participante_id_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='id_escola',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='id_participante',
        ),
    ]
