# Generated by Django 5.2.3 on 2025-06-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_escola_codigo_participante_codigo_prova_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabaritolido',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
