# Generated by Django 5.2.3 on 2025-06-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gabaritolido_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='id_prova',
        ),
    ]
