# Generated by Django 5.2.3 on 2025-06-16 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_escola_codigo_alter_escola_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabaritolido',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prova',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gabaritolido',
            unique_together={('codigo', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('codigo', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='prova',
            unique_together={('codigo', 'user')},
        ),
    ]
